apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.11
    helm:
      parameters:
      - name: "installCRDs"
        value: "true"
      # Thêm cấu hình resources để thỏa mãn Gatekeeper
      - name: "resources.limits.cpu"
        value: "100m"
      - name: "resources.limits.memory"
        value: "256Mi"
      - name: "resources.requests.cpu"
        value: "50m"
      - name: "resources.requests.memory"
        value: "128Mi"
      # Áp dụng tương tự cho các thành phần khác nếu Gatekeeper vẫn chặn
      - name: "webhook.resources.limits.cpu"
        value: "100m"
      - name: "webhook.resources.limits.memory"
        value: "256Mi"
      - name: "certController.resources.limits.cpu"
        value: "100m"
      - name: "certController.resources.limits.memory"
        value: "256Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true