apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret-sync
  namespace: demo
spec:
  refreshInterval: "30s" # Đảm bảo < 60s như yêu cầu của đề bài
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: my-db-secret # Tên K8s Secret sẽ được tạo ra tự động
    creationPolicy: Owner
  data:
    - secretKey: password # Key trong K8s Secret
      remoteRef:
        key: production/db/password # Tên Key trên AWS Secrets Manager