apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: demo
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1 # Region của bạn
      auth:
        secretRef:
          # Tạo bằng lệnh: kubectl create secret generic aws-creds --from-literal=access-key=X --from-literal=secret-access-key=Y -n demo
          # KHÔNG COMMIT FILE CHỨA CREDS NÀY LÊN GIT
          accessKeyIDSecretRef:
            name: aws-creds
            key: access-key
          secretAccessKeySecretRef:
            name: aws-creds
            key: secret-access-key